import type { FC } from "react"
import Head from "next/head"

type LayoutProps = {
    title: string
    children: React.ReactNode
}

const Layout: FC<LayoutProps> = ({ title, children }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">{children}</main>
        </>
    )
}

export default Layout
